/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dialog;
import ClassAbsensi.Kelas;
import ClassAbsensi.KelasDAO;
import ClassAbsensi.Koneksi;
import ClassAbsensi.QRCodeGenerator;
import ClassAbsensi.Koneksi;
import ClassAbsensi.Siswa;
import ClassAbsensi.SiswaDAO;
import Frame.panelSiswa;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author siti novi triana
/**
 *
 * @author siti novi triana
 */
public class DialogTambahSiswa extends javax.swing.JDialog {
private panelSiswa panelsiswa;
    /**
     * Creates new form DialogTambahSiswa
     */
    public DialogTambahSiswa() {
        initComponents();
       loadComboBox();
       panelsiswa = new panelSiswa();
    }
    // Method untuk load semua ComboBox saat form dibuka

    private void loadComboBox() {
        loadComboBoxJenisKelamin();
        loadComboBoxKelas();
    }

    // Method untuk load ComboBox Jenis Kelamin
    private void loadComboBoxJenisKelamin() {
        cJK.removeAllItems();
        cJK.addItem("-- Pilih Jenis Kelamin --");
        cJK.addItem("Laki-laki");
        cJK.addItem("Perempuan");
        cJK.setSelectedIndex(0);
    }

    // Method untuk load ComboBox Kelas dari database
    private void loadComboBoxKelas() {
    cKelas.removeAllItems();
    cKelas.addItem("-- Pilih Kelas --");
    
    // Deklarasi dan inisialisasi KelasDAO
    KelasDAO kelasDAO = new KelasDAO();
    
    // Load semua kelas dari database
    List<Kelas> listKelas = kelasDAO.loadAllKelas();
    
    // Cek jika data kelas kosong
    if (listKelas.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Data kelas masih kosong!\n"
                + "Silakan tambahkan data kelas terlebih dahulu.",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Tambahkan tingkat kelas ke ComboBox
    for (Kelas kelas : listKelas) {
        cKelas.addItem(String.valueOf(kelas.getTingkat()));
    }
    
    cKelas.setSelectedIndex(0);
}
    private void resetForm (){
        tNIS.setText("");
        tNama.setText("");
        cKelas.setSelectedIndex(0);
        cJK.setSelectedIndex(0);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tNIS = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cKelas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cJK = new javax.swing.JComboBox<>();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("NIS");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nama Siswa");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Kelas");

        cKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        cJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cKelas, 0, 378, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNama)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNIS)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cJK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cJK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnBatal.setBackground(new java.awt.Color(149, 165, 166));
        btnBatal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(39, 174, 96));
        btnSimpan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TAMBAH SISWA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 388, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
            "Batalkan perubahan?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    String nisStr = tNIS.getText().trim();
    String namaSiswa = tNama.getText().trim();
    String jenisKelamin = cJK.getSelectedItem().toString();
    
    // Ambil ID kelas dari ComboBox
    int idKelas = 0;
    if (cKelas.getSelectedIndex() > 0) {
        String kelasStr = cKelas.getSelectedItem().toString();
        idKelas = Integer.parseInt(kelasStr);
    }
    
    // ========== VALIDASI INPUT ==========
    if (nisStr.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "NIS tidak boleh kosong!",
                "Validasi Error",
                JOptionPane.WARNING_MESSAGE);
        tNIS.requestFocus();
        return;
    }
    
    if (!nisStr.matches("\\d+")) {
        JOptionPane.showMessageDialog(this,
                "NIS harus berupa angka!",
                "Validasi Error",
                JOptionPane.WARNING_MESSAGE);
        tNIS.requestFocus();
        return;
    }
    
    // Convert NIS ke int
    int nis = 0;
    try {
        nis = Integer.parseInt(nisStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Format NIS tidak valid!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        tNIS.requestFocus();
        return;
    }
    
    // Cek apakah NIS sudah terdaftar
    SiswaDAO siswaDAO = new SiswaDAO();
    if (siswaDAO.isNisExist(nis)) {
        JOptionPane.showMessageDialog(this,
                "NIS " + nis + " sudah terdaftar!\nGunakan NIS yang berbeda.",
                "Validasi Error",
                JOptionPane.WARNING_MESSAGE);
        tNIS.requestFocus();
        return;
    }
    
    if (namaSiswa.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Nama siswa tidak boleh kosong!",
                "Validasi Error",
                JOptionPane.WARNING_MESSAGE);
        tNama.requestFocus();
        return;
    }
    
    if (idKelas == 0 || cKelas.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this,
                "Kelas harus dipilih!",
                "Validasi Error",
                JOptionPane.WARNING_MESSAGE);
        cKelas.requestFocus();
        return;
    }
    
    if (cJK.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this,
                "Jenis kelamin harus dipilih!",
                "Validasi Error",
                JOptionPane.WARNING_MESSAGE);
        cJK.requestFocus();
        return;
    }
    
    // Convert jenis kelamin ke format database (L/P)
    String jk = jenisKelamin.equals("Laki-Laki") ? "L" : "P";
    
    // ========== KONFIRMASI ==========
    int confirm = JOptionPane.showConfirmDialog(this,
            "Simpan data siswa baru dengan informasi:\n\n"
            + "NIS           : " + nis + "\n"
            + "Nama Siswa    : " + namaSiswa + "\n"
            + "Kelas         : " + idKelas + "\n"
            + "Jenis Kelamin : " + jenisKelamin + "\n\n"
            + "Data QR Code akan disimpan di database.\n"
            + "File QR dapat di-download di menu Generate QR.\n\n"
            + "Apakah Anda yakin?",
            "Konfirmasi Tambah Data",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
    
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            // ========== BUAT OBJECT SISWA ==========
            Siswa siswa = new Siswa();
            siswa.setNis(nis);
            siswa.setNamaSiswa(namaSiswa);
            siswa.setIdKelas(idKelas);
            siswa.setJenisKelamin(jk);
            siswa.setQrCode("QR" + nis); // ✅ Simpan sebagai string QR code
            siswa.setStatus("Aktif");
            
            // ========== SIMPAN KE DATABASE ==========
            boolean success = siswaDAO.tambahSiswa(siswa);
            
            if (success) {
                JOptionPane.showMessageDialog(this,
                        "✓ Data siswa berhasil ditambahkan!\n\n"
                        + "NIS: " + nis + "\n"
                        + "Nama: " + namaSiswa + "\n"
                        + "QR Code: QR" + nis + "\n\n"
                        + "Untuk mendapatkan file QR Code (PNG),\n"
                        + "silakan download di menu Generate QR.",
                        "Berhasil",
                        JOptionPane.INFORMATION_MESSAGE);
                
                // Refresh table di panel siswa
                if (getParent() instanceof panelSiswa) {
                    panelSiswa parent = (panelSiswa) getParent();
                    parent.refreshTableData();
                }
                
                dispose();
                
            } else {
                JOptionPane.showMessageDialog(this,
                        "✗ Gagal menyimpan data siswa ke database!\n"
                        + "Silakan coba lagi atau hubungi administrator.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "✗ Error: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    

       
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cJK;
    private javax.swing.JComboBox<String> cKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tNIS;
    private javax.swing.JTextField tNama;
    // End of variables declaration//GEN-END:variables
}
