 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package absensiapp;
import ClassAbsensi.Koneksi;
import ClassAbsensi.QRCodeGenerator;
import ClassAbsensi.Koneksi;
import ClassAbsensi.Siswa;
import ClassAbsensi.SiswaDAO;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author siti novi triana
/**
 *
 * @author siti novi triana
 */
public class DialogTambahSiswa extends javax.swing.JDialog {

    /**
     * Creates new form DialogTambahSiswa
     */
    public DialogTambahSiswa() {
        initComponents();
       
    }
    // Method untuk load semua ComboBox saat form dibuka

    private void loadComboBox() {
        loadComboBoxJenisKelamin();
        loadComboBoxKelas();
    }

    // Method untuk load ComboBox Jenis Kelamin
    private void loadComboBoxJenisKelamin() {
        cJK.removeAllItems(); //Hapus semua item yang ada di ComboBox
        cJK.addItem("-- Pilih Jenis Kelamin --"); //Tambahkan item pertama ke ComboBox berupa teks
        cJK.addItem("Laki-laki");
        cJK.addItem("Perempuan");
        cJK.setSelectedIndex(0);
    }

    // Method untuk load ComboBox Kelas dari database
    private void loadComboBoxKelas() {
        cKelas.removeAllItems(); //Hapus semua item yang ada di ComboBox
        cKelas.addItem("-- Pilih Kelas --"); //Tambahkan item pertama ke ComboBox berupa teks

        SiswaDAO siswaDAO = new SiswaDAO();
        List<Integer> listKelas = siswaDAO.getDistinctKelas();

        if (listKelas.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Data kelas masih kosong!\n"
                    + "Silakan tambahkan data kelas terlebih dahulu.",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        for (Integer idKelas : listKelas) {
            cKelas.addItem(String.valueOf(idKelas));
        }

        cKelas.setSelectedIndex(0);
    }
    private void resetForm (){
        tNIS.setText("");
        tNama.setText("");
        cKelas.setSelectedIndex(0);
        cJK.setSelectedIndex(0);
        lblCode.setIcon(null);
        lblCode.setText("QR Code Preview");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tNIS = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cKelas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cJK = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        lblCode = new javax.swing.JLabel();
        lableCode = new javax.swing.JLabel();
        bBuat = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("NIS");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nama Siswa");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Kelas");

        cKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kelas 1", "Kelas 2", "Kelas 3", "Kelas 4", "Kelas 5", "Kelas 6" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        cJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setMaximumSize(new java.awt.Dimension(150, 127));
        jPanel3.setPreferredSize(new java.awt.Dimension(150, 127));

        lblCode.setText("QR");

        lableCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableCode.setText("QR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(lblCode)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lableCode, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lableCode, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCode)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bBuat.setText("Buat QR");
        bBuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cKelas, 0, 378, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tNama)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tNIS)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cJK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bBuat)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cJK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBuat)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnBatal.setBackground(new java.awt.Color(149, 165, 166));
        btnBatal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(39, 174, 96));
        btnSimpan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TAMBAH SISWA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 541, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
            "Batalkan perubahan?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
                                        
    String nis = tNIS.getText().trim();
    String namaSiswa = tNama.getText().trim();
    
    // ✅ CONVERT JENIS KELAMIN KE FORMAT DATABASE
    String jenisKelaminDisplay = cJK.getSelectedItem().toString();
    String jenisKelamin = "";
    
    if (jenisKelaminDisplay.equals("Laki-laki")) {
        jenisKelamin = "L";
    } else if (jenisKelaminDisplay.equals("Perempuan")) {
        jenisKelamin = "P";
    }
    
    // Parse kelas
    int idKelas = 0;
    if (cKelas.getSelectedIndex() > 0) { //Jika index ComboBox lebih dari 0.
        try {
            //Ambil item kelas yang dipilih di ComboBox, lalu ubah ke String.
            String selectedKelas = cKelas.getSelectedItem().toString(); 
            idKelas = Integer.parseInt(selectedKelas); //Ubah teks kelas menjadi angka dan simpan ke idKelas.
        } catch (NumberFormatException e) { // tangkap error teks yg tidak bisa diubah ke angka misal huruf
            JOptionPane.showMessageDialog(this, //Tampilkan peringatan bahwa format kelas tidak valid.
                "Format kelas tidak valid!",
                "Validasi Error",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
    }
    
    String qrCode = nis;
    
    // Validasi input
    if (nis.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "NIS tidak boleh kosong!",
            "Validasi Error",
            JOptionPane.WARNING_MESSAGE);
        tNIS.requestFocus();
        return;
    }
    
    if (!nis.matches("\\d+")) {
        JOptionPane.showMessageDialog(this,
            "NIS harus berupa angka!",
            "Validasi Error",
            JOptionPane.WARNING_MESSAGE);
        tNIS.requestFocus();
        return;
    }
    
    if (namaSiswa.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Nama siswa tidak boleh kosong!",
            "Validasi Error",
            JOptionPane.WARNING_MESSAGE);
        tNama.requestFocus();
        return;
    }
    
    if (idKelas == 0 || cKelas.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this,
            "Kelas harus dipilih!",
            "Validasi Error",
            JOptionPane.WARNING_MESSAGE);
        cKelas.requestFocus();
        return;
    }
    
    if (cJK.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this,
            "Jenis kelamin harus dipilih!",
            "Validasi Error",
            JOptionPane.WARNING_MESSAGE);
        cJK.requestFocus();
        return;
    }
    
    if (qrCode.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "QR Code belum dibuat!\n" +
            "Klik tombol 'Buat QR' terlebih dahulu.",
            "Validasi Error",
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Konfirmasi - tampilkan full text untuk user
    int confirm = JOptionPane.showConfirmDialog(this,
        "Simpan data siswa dengan informasi:\n\n" +
        "NIS           : " + nis + "\n" +
        "Nama Siswa    : " + namaSiswa + "\n" +
        "Kelas         : " + idKelas + "\n" +
        "Jenis Kelamin : " + jenisKelaminDisplay + "\n\n" +
        "Apakah Anda yakin ingin menyimpan data ini?",
        "Konfirmasi Simpan Data",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);
    
    if (confirm == JOptionPane.YES_OPTION) {
        // ✅ GENERATE DAN SAVE QR CODE KE FILE
        String qrFolderPath = "qr_codes"; // Folder untuk menyimpan QR
        String qrFileName = "QR_" + nis + ".png";
        String qrFilePath = qrFolderPath + File.separator + qrFileName;
        
        // Generate QR Code file kenapa pakai boolean?
        //karena method generateQRFile yang dipanggil mengembalikan nilai berhasil / gagal.
        boolean qrGenerated = QRCodeGenerator.generateQRFile(qrCode, qrFilePath, 300, 300);
        
        if (!qrGenerated) {
            JOptionPane.showMessageDialog(this,
                "⚠ Gagal membuat file QR Code!\n" +
                "Data siswa tidak akan disimpan.",
                "Error QR Code",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Simpan data siswa ke database
        Siswa siswa = new Siswa();
        siswa.setNis(nis);
        siswa.setNamaSiswa(namaSiswa);
        siswa.setIdKelas(idKelas);
        siswa.setJenisKelamin(jenisKelamin);
        siswa.setQrCode(qrCode);
        
        SiswaDAO siswaDAO = new SiswaDAO();
        boolean success = siswaDAO.tambahSiswa(siswa);
        
        if (success) {
            JOptionPane.showMessageDialog(this,
                "✓ Data siswa berhasil disimpan!\n" +
                "✓ QR Code tersimpan di: " + qrFilePath,
                "Berhasil",
                JOptionPane.INFORMATION_MESSAGE);
            
            resetForm();
            dispose();
            
        } else {
            JOptionPane.showMessageDialog(this,
                "✗ Gagal menyimpan data siswa!\n\n" +
                "Kemungkinan penyebab:\n" +
                "• NIS sudah terdaftar\n" +
                "• Koneksi database bermasalah\n" +
                "• Data tidak valid\n\n" +
                "File QR Code telah dibuat di: " + qrFilePath,
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    

       
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void bBuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuatActionPerformed
        try {
        // Ambil data dari form
        String nis = tNIS.getText().trim();
        String namaSiswa = tNama.getText().trim();
        
        // Validasi minimal NIS
        if (nis.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "NIS harus diisi terlebih dahulu!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            tNIS.requestFocus();
            return;
        }
        
        if (namaSiswa.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Nama Siswa harus diisi terlebih dahulu!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            tNama.requestFocus();
            return;
        }
        
        String kelas = cKelas.getSelectedItem().toString();
        String jenisKelamin = cJK.getSelectedItem().toString();
        
        // Buat data untuk QR Code
        String qrData = "NIS: " + nis + "\n" +
                       "Nama: " + namaSiswa + "\n" +
                       "Kelas: " + kelas + "\n" +
                       "Jenis Kelamin: " + jenisKelamin;
        
        // Generate QR Code
        int size = 300;
        String charset = "UTF-8";
        //Buat sebuah HashMap yang key-nya bertipe EncodeHintType dan value-nya bertipe Object,
        //lalu simpan di variabel bernama hints.
        Map<EncodeHintType, Object> hints = new HashMap<>();
        //Masukkan ke dalam hints: key ERROR_CORRECTION dengan value ErrorCorrectionLevel.H.
        hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);
        //Masukkan pengaturan CHARACTER_SET dengan nilai charset (misal: "UTF-8").
        hints.put(EncodeHintType.CHARACTER_SET, charset);
        //Tambahkan pengaturan margin sebesar 1 ke dalam hints.
        hints.put(EncodeHintType.MARGIN, 1);
        
        BitMatrix matrix = new MultiFormatWriter().encode(
            qrData,
            BarcodeFormat.QR_CODE,
            size,
            size,
            hints
        );
        
        // Convert ke BufferedImage
        BufferedImage qrImage = MatrixToImageWriter.toBufferedImage(matrix);
        
        // Resize ke ukuran panel (150x127)
        Image scaledImage = qrImage.getScaledInstance(150, 127, Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(scaledImage);
        
        // Tampilkan di label
        lblCode.setText(""); // Hapus text "QR"
        lblCode.setIcon(icon);
        lblCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        JOptionPane.showMessageDialog(this,
            "✓ QR Code berhasil dibuat!",
            "Berhasil",
            JOptionPane.INFORMATION_MESSAGE);
        
    } catch (WriterException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
            "✗ Gagal membuat QR Code: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_bBuatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuat;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cJK;
    private javax.swing.JComboBox<String> cKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lableCode;
    private javax.swing.JLabel lblCode;
    private javax.swing.JTextField tNIS;
    private javax.swing.JTextField tNama;
    // End of variables declaration//GEN-END:variables
}
