/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package absensiapp;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author MyBook Hype AMD
 */
public class FrameLogin extends javax.swing.JFrame {

    /**
     * Creates new form CharisFrame
     */
    public FrameLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        tUserName = new panelcustom.TextFieldCustom();
        tPassword = new panelcustom.TextFieldCustom();
        btnLogin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absensiapp/icon/icons8-open-book-90.png"))); // NOI18N
        jLabel3.setText("SD ISLAM KHADIJAH");
        jLabel3.setAlignmentY(0.0F);
        jLabel3.setIconTextGap(30);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 400, 70));

        tUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tUserName.setText("Username");
        tUserName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tUserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absensiapp/icon/icons8-person-40 (2).png"))); // NOI18N
        tUserName.setIconX(5);
        tUserName.setInheritsPopupMenu(true);
        tUserName.setRoundBottomLeft(5);
        tUserName.setRoundBottomRight(5);
        tUserName.setRoundTopLeft(5);
        tUserName.setRoundTopRight(5);
        tUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(tUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 270, 40));

        tPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tPassword.setText("Password");
        tPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absensiapp/icon/icons8-padlock-40 (1).png"))); // NOI18N
        tPassword.setIconX(5);
        tPassword.setInheritsPopupMenu(true);
        tPassword.setRoundBottomLeft(5);
        tPassword.setRoundBottomRight(5);
        tPassword.setRoundTopLeft(5);
        tPassword.setRoundTopRight(5);
        getContentPane().add(tPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 270, 40));

        btnLogin.setBackground(new java.awt.Color(0, 51, 51));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setAlignmentY(0.0F);
        btnLogin.setBorder(null);
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setMargin(new java.awt.Insets(3, 14, 3, 14));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 270, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absensiapp/image/h1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 470, 350));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absensiapp/image/logo.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, 80));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOGIN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absensiapp/image/BG.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 504));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    private void tUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUserNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private panelcustom.TextFieldCustom tPassword;
    private panelcustom.TextFieldCustom tUserName;
    // End of variables declaration//GEN-END:variables
}
