/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package absensiapp;

/**
 *
 * @author LENOVO
 */
public class PanelCharis extends javax.swing.JPanel {

    /**
     * Creates new form PanelCharis
     */
    public PanelCharis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sudutPanel1 = new absensiapp.custom.SudutPanel();
        jLabel2 = new javax.swing.JLabel();
        sudutPanel2 = new absensiapp.custom.SudutPanel();
        jLabel3 = new javax.swing.JLabel();

        sudutPanel1.setBackground(new java.awt.Color(102, 102, 255));
        sudutPanel1.setRoundBottomLeft(50);
        sudutPanel1.setRoundBottomRight(50);
        sudutPanel1.setRoundTopLeft(50);
        sudutPanel1.setRoundTopRight(50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Siswa");

        javax.swing.GroupLayout sudutPanel1Layout = new javax.swing.GroupLayout(sudutPanel1);
        sudutPanel1.setLayout(sudutPanel1Layout);
        sudutPanel1Layout.setHorizontalGroup(
            sudutPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sudutPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        sudutPanel1Layout.setVerticalGroup(
            sudutPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sudutPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 72, Short.MAX_VALUE))
        );

        sudutPanel2.setBackground(new java.awt.Color(102, 102, 255));
        sudutPanel2.setRoundBottomLeft(50);
        sudutPanel2.setRoundBottomRight(50);
        sudutPanel2.setRoundTopLeft(50);
        sudutPanel2.setRoundTopRight(50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kelas");

        javax.swing.GroupLayout sudutPanel2Layout = new javax.swing.GroupLayout(sudutPanel2);
        sudutPanel2.setLayout(sudutPanel2Layout);
        sudutPanel2Layout.setHorizontalGroup(
            sudutPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sudutPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        sudutPanel2Layout.setVerticalGroup(
            sudutPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sudutPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sudutPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sudutPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sudutPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(sudutPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(242, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private absensiapp.custom.SudutPanel sudutPanel1;
    private absensiapp.custom.SudutPanel sudutPanel2;
    // End of variables declaration//GEN-END:variables
}
