/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelPengaturan;

import java.awt.Color;
import java.awt.Font;
import javax.swing.table.JTableHeader;
import ClassAbsensi.User;
import ClassAbsensi.UserDB;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author MyBook Hype AMD
 */
public class panelKelolaUser1 extends javax.swing.JPanel {

    /**
     * Creates new form panelKelolaUser
     */
    public panelKelolaUser1() {
        initComponents();
        colorTable();
        tblUser.setColumnSelectionAllowed(false);
        tblUser.setRowSelectionAllowed(true);
        loadDataUser();
        
    }
    
    private void loadDataUser() {
    DefaultTableModel model = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Semua cell gak bisa diedit
        }
    };
    model.addColumn("ID");
    model.addColumn("Username");
    model.addColumn("Password");
    model.addColumn("Nama");
    model.addColumn("Role");
    
    // Pakai UserDAO untuk ambil semua user
    UserDB userDAO = new UserDB();
    List<User> listUser = userDAO.getAllUsers();
    
    for (User user : listUser) {
        Object[] row = {
            user.getUserId(),
            user.getUsername(),
            "********",
            user.getNama(),
            user.getRole()
        };
        model.addRow(row);
    }
    
    tblUser.setModel(model);
}
public void colorTable(){
            JTableHeader header = tblUser.getTableHeader();
            header.setBackground(new Color(0, 153, 255)); // biru
            header.setForeground(Color.WHITE);            // teks putih
            header.setFont(new Font("Segoe UI", Font.BOLD, 12));
            tblUser.setGridColor(new Color(0xE2E8F0)); // Abu sangat terang

            // === CUSTOM SELECTION COLOR ===
            tblUser.setSelectionBackground(new Color(0xBFDBFE)); // Biru muda terang
            tblUser.setSelectionForeground(new Color(0x1E3A8A)); // Biru tua

            // === ROW HEIGHT & FONT ===
            tblUser.setRowHeight(28);
            tblUser.setFont(new Font("Segoe UI", Font.PLAIN, 13));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanelCustom4 = new ClassTambahan.JPanelCustom();
        jLabel21 = new javax.swing.JLabel();
        tUsername = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tPassword = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cRole = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(241, 245, 249));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Kelola User");

        tblUser.setForeground(new java.awt.Color(51, 65, 85));
        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Username", "Password", "Role"
            }
        ));
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUser);
        tblUser.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButton1.setBackground(new java.awt.Color(34, 197, 94));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(239, 68, 68));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Hapus");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(245, 158, 11));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Ubah");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(100, 116, 139));
        jButton8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Reset");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jPanelCustom4.setBackground(new java.awt.Color(204, 204, 255));
        jPanelCustom4.setRoundBottomLeft(22);
        jPanelCustom4.setRoundBottomRight(22);
        jPanelCustom4.setRoundTopLeft(22);
        jPanelCustom4.setRoundTopRight(22);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setText("Username");

        tUsername.setBackground(new java.awt.Color(248, 250, 252));
        tUsername.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tUsername.setForeground(new java.awt.Color(30, 41, 59));
        tUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(147, 197, 253), 2, true));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setText("Password");

        tPassword.setBackground(new java.awt.Color(248, 250, 252));
        tPassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(147, 197, 253), 2, true));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setText("Nama");

        tNama.setBackground(new java.awt.Color(248, 250, 252));
        tNama.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tNama.setForeground(new java.awt.Color(30, 41, 59));
        tNama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(147, 197, 253), 2, true));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("Role");

        cRole.setBackground(new java.awt.Color(248, 250, 252));
        cRole.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cRole.setForeground(new java.awt.Color(30, 41, 59));
        cRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Guru" }));
        cRole.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(147, 197, 253), 2, true));

        javax.swing.GroupLayout jPanelCustom4Layout = new javax.swing.GroupLayout(jPanelCustom4);
        jPanelCustom4.setLayout(jPanelCustom4Layout);
        jPanelCustom4Layout.setHorizontalGroup(
            jPanelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tNama)
                    .addComponent(cRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tUsername)
                    .addGroup(jPanelCustom4Layout.createSequentialGroup()
                        .addGroup(jPanelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCustom4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel21)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(0, 130, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCustom4Layout.setVerticalGroup(
            jPanelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cRole, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(382, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       int selectedRow = tblUser.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this,
            "Pilih user yang akan diubah!",
            "Peringatan",
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    try {
        // Ambil data LANGSUNG dari tabel (tidak perlu query lagi)
        String userId = tblUser.getValueAt(selectedRow, 0).toString();
        String username = tblUser.getValueAt(selectedRow, 1).toString();
        String nama = tblUser.getValueAt(selectedRow, 3).toString();
        String role = tblUser.getValueAt(selectedRow, 4).toString();
        
        System.out.println("Data dari tabel:");
        System.out.println("  - ID: " + userId);
        System.out.println("  - Username: " + username);
        System.out.println("  - Nama: " + nama);
        System.out.println("  - Role: " + role);
        
        // Buat object User manual (tidak perlu getUserById)
        User user = new User();
        user.setUserId(Integer.parseInt(userId));
        user.setUsername(username);
        user.setNama(nama);
        user.setRole(role);
        
        // Validasi user tidak null
        if (user.getUsername() == null || user.getUsername().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Data user tidak valid!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Buka dialog
        dialogUbahUser dialog = new dialogUbahUser(
            (java.awt.Frame) SwingUtilities.getWindowAncestor(this), 
            true, 
            user
        );
        dialog.setVisible(true);
        
        // Refresh tabel
        if (dialog.isSaved()) {
            loadDataUser();
        }
        
    } catch (Exception e) {
        System.out.println("❌ Error btnUbah: " + e.getMessage());
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
            "Terjadi kesalahan: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       clearForm();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
       int selectedRow = tblUser.getSelectedRow();
    
    // Pastikan ada baris yang dipilih
    if (selectedRow != -1) {
        // Ambil data dari tabel (sesuai index kolom)
        String userId = tblUser.getValueAt(selectedRow, 0).toString();
        String username = tblUser.getValueAt(selectedRow, 1).toString();
        // Password tidak diambil karena di-mask (********)
        String nama = tblUser.getValueAt(selectedRow, 3).toString();
        String role = tblUser.getValueAt(selectedRow, 4).toString();
        
        // Isi ke form
        tUsername.setText(username);
        tPassword.setText(""); // Kosongkan password untuk keamanan
        tNama.setText(nama);
        cRole.setSelectedItem(role); // Set ComboBox sesuai role
        
        // Optional: Simpan userId untuk keperluan update/delete
        // Bisa pakai variable global atau hidden field
        System.out.println("✓ Data terpilih - ID: " + userId + ", Nama: " + nama);
    }
    }//GEN-LAST:event_tblUserMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String username = tUsername.getText().trim();
    String password = new String(tPassword.getPassword()).trim();
    String nama = tNama.getText().trim();
    String role = cRole.getSelectedItem().toString();
    
    // Validasi input
    if (username.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Username tidak boleh kosong!",
            "Validasi Error",
            JOptionPane.WARNING_MESSAGE);
        tUsername.requestFocus();
        return;
    }
    
    if (password.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Password tidak boleh kosong!",
            "Validasi Error",
            JOptionPane.WARNING_MESSAGE);
        tPassword.requestFocus();
        return;
    }
    
    if (nama.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Nama tidak boleh kosong!",
            "Validasi Error",
            JOptionPane.WARNING_MESSAGE);
        tNama.requestFocus();
        return;
    }
    
    // Konfirmasi
    int confirm = JOptionPane.showConfirmDialog(this,
        "Tambah user baru dengan data:\n" +
        "Username: " + username + "\n" +
        "Nama: " + nama + "\n" +
        "Role: " + role + "\n\n" +
        "Lanjutkan?",
        "Konfirmasi Tambah",
        JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        // Buat object User
        User user = new User();
        user.setUsername(username);
        user.setPassword(password);
        user.setNama(nama);
        user.setRole(role);
        
        // Panggil method dari UserDAO
        UserDB userDAO = new UserDB();
        boolean success = userDAO.addUser(user);
        
        if (success) {
            JOptionPane.showMessageDialog(this,
                "✓ User berhasil ditambahkan!",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE);
            
            // Clear form
            clearForm();
            
            // Refresh tabel
            loadDataUser();
        } else {
            JOptionPane.showMessageDialog(this,
                "✗ Gagal menambahkan user!\n" +
                "Username mungkin sudah digunakan.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     int selectedRow = tblUser.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this,
            "Pilih user yang akan dihapus!",
            "Peringatan",
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String userId = tblUser.getValueAt(selectedRow, 0).toString();
    String username = tblUser.getValueAt(selectedRow, 1).toString();
    String nama = tblUser.getValueAt(selectedRow, 3).toString();
    
    // Konfirmasi hapus
    int confirm = JOptionPane.showConfirmDialog(this,
        "Hapus user:\n" +
        "Username: " + username + "\n" +
        "Nama: " + nama + "\n\n" +
        "Data yang dihapus tidak dapat dikembalikan!\n" +
        "Lanjutkan?",
        "Konfirmasi Hapus",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE);
    
    if (confirm == JOptionPane.YES_OPTION) {
        UserDB userDAO = new UserDB();
        boolean success = userDAO.deleteUser(Integer.parseInt(userId));
        
        if (success) {
            JOptionPane.showMessageDialog(this,
                "✓ User berhasil dihapus!",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE);
            
            clearForm();
            loadDataUser();
        } else {
            JOptionPane.showMessageDialog(this,
                "✗ Gagal menghapus user!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButton5ActionPerformed
private void clearForm() {
    tUsername.setText("");
    tPassword.setText("");
    tNama.setText("");
    cRole.setSelectedIndex(0); // Set ke pilihan pertama
    tUsername.requestFocus();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cRole;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private ClassTambahan.JPanelCustom jPanelCustom4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tNama;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUsername;
    private javax.swing.JTable tblUser;
    // End of variables declaration//GEN-END:variables
}
