/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelPengaturan;

import ClassAbsensi.AbsensiDAO;
import java.text.SimpleDateFormat;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author MyBook Hype AMD
 */
public class panelJamAbsen extends javax.swing.JPanel {
private AbsensiDAO absensiDAO;
    /**
     * Creates new form panelJamAbsen
     */
    public panelJamAbsen() {
        initComponents();
        absensiDAO = new AbsensiDAO();
        loadJamAbsensi();
    }
private void loadJamAbsensi() {
    try {
        Map<String, Object> jamAbsensi = absensiDAO.getJamAbsensi();
        
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
        
        java.sql.Time jamMasuk = (java.sql.Time) jamAbsensi.get("jam_masuk");
        Integer toleransi = (Integer) jamAbsensi.get("toleransi");
        
        tJamMasuk.setText(sdf.format(jamMasuk));
        tToleransi.setText(String.valueOf(toleransi));
        
        System.out.println("✅ Data jam absensi berhasil dimuat");
        
    } catch (Exception e) {
        System.err.println("❌ Error loadJamAbsensi: " + e.getMessage());
        e.printStackTrace();
    }
}
private void simpanJamAbsensi() {
    try {
        String jamMasuk = tJamMasuk.getText().trim();
        String toleransiStr = tToleransi.getText().trim();
        
        // Validasi input kosong
        if (jamMasuk.isEmpty() || toleransiStr.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Semua field harus diisi!",
                "Validasi Error",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Validasi format jam
        if (!jamMasuk.matches("\\d{2}:\\d{2}")) {
            JOptionPane.showMessageDialog(this,
                "Format jam harus HH:mm (contoh: 07:00)",
                "Validasi Error",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Validasi toleransi
        int toleransi;
        try {
            toleransi = Integer.parseInt(toleransiStr);
            
            if (toleransi < 0 || toleransi > 60) {
                JOptionPane.showMessageDialog(this,
                    "Toleransi harus antara 0-60 menit!",
                    "Validasi Error",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Toleransi harus berupa angka!",
                "Validasi Error",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Hitung batas telat untuk preview
        String[] jamSplit = jamMasuk.split(":");
        int jam = Integer.parseInt(jamSplit[0]);
        int menit = Integer.parseInt(jamSplit[1]) + toleransi;
        
        if (menit >= 60) {
            jam += menit / 60;
            menit = menit % 60;
        }
        
        String batasTelat = String.format("%02d:%02d", jam, menit);
        
        // Konfirmasi
        int confirm = JOptionPane.showConfirmDialog(this,
            "Simpan pengaturan jam absensi?\n\n" +
            "Jam Masuk    : " + jamMasuk + "\n" +
            "Toleransi    : " + toleransi + " menit\n" +
            "Batas Telat  : " + batasTelat + "\n\n" +
            "Siswa yang scan QR sebelum " + batasTelat + " → Hadir\n" +
            "Siswa yang scan QR setelah " + batasTelat + " → Telat",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION);
        
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        // Simpan ke database
        boolean success = absensiDAO.updateJamAbsensi(jamMasuk, toleransi);
        
        if (success) {
            JOptionPane.showMessageDialog(this,
                "✓ Pengaturan jam absensi berhasil disimpan!",
                "Berhasil",
                JOptionPane.INFORMATION_MESSAGE);
            
            loadJamAbsensi();
            
        } else {
            JOptionPane.showMessageDialog(this,
                "✗ Gagal menyimpan pengaturan jam absensi!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        
    } catch (Exception e) {
        System.err.println("❌ Error simpanJamAbsensi: " + e.getMessage());
        e.printStackTrace();
        
        JOptionPane.showMessageDialog(this,
            "Terjadi kesalahan: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tJamMasuk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tToleransi = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Jam Absensi");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel2.setText("Atur Jam Absensi Untuk Semua SIswa");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Jam masuk");

        jLabel5.setText("Digunakan untuk menentukan maksimal siswa dapat melakukan presensi sebelum terlambat, gunakan format menit( contoh : 15, 20, 25)");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Toleransi  Keterlambatan");

        tJamMasuk.setText("HH:mm");
        tJamMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJamMasukActionPerformed(evt);
            }
        });

        jLabel7.setText("Gunakan Format HH:mm(jam:menit) untuk mengatur jam masuk");

        tToleransi.setText("menit");

        btnSimpan.setBackground(new java.awt.Color(0, 204, 0));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tToleransi, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tJamMasuk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tJamMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tToleransi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tJamMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJamMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJamMasukActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        simpanJamAbsensi();
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tJamMasuk;
    private javax.swing.JTextField tToleransi;
    // End of variables declaration//GEN-END:variables
}
