package Frame;


import ClassAbsensi.LoginDB;
import ClassAbsensi.User;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import ClassAbsensi.Session;

public class FrameLogin extends javax.swing.JFrame {

    /**
     * Creates new form CharisFrame
     */
    public FrameLogin() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tPassword = new ClassTambahan.PasswordField();
        tUsername = new ClassTambahan.TextField();
        jLabel3 = new javax.swing.JLabel();
        showPassword = new javax.swing.JCheckBox();
        btnLogin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tPassword.setForeground(new java.awt.Color(0, 0, 0));
        tPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikon_white/gembok _ogin.png"))); // NOI18N
        tPassword.setIconX(2);
        tPassword.setRoundBottomLeft(5);
        tPassword.setRoundBottomRight(5);
        tPassword.setRoundTopLeft(5);
        tPassword.setRoundTopRight(5);
        tPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 270, 40));

        tUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tUsername.setText("Username");
        tUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikon_white/username.png"))); // NOI18N
        tUsername.setIconX(5);
        tUsername.setRoundBottomLeft(5);
        tUsername.setRoundBottomRight(5);
        tUsername.setRoundTopLeft(5);
        tUsername.setRoundTopRight(5);
        getContentPane().add(tUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 270, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikon_white/book-login.png"))); // NOI18N
        jLabel3.setText("SD ISLAM KHADIJAH");
        jLabel3.setAlignmentY(0.0F);
        jLabel3.setIconTextGap(30);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 400, 70));

        showPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showPassword.setForeground(new java.awt.Color(255, 255, 255));
        showPassword.setText("Show Password");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        btnLogin.setBackground(new java.awt.Color(0, 51, 51));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setAlignmentY(0.0F);
        btnLogin.setBorder(null);
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setMargin(new java.awt.Insets(3, 14, 3, 14));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 270, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikon_blue/h1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 470, 350));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikon_blue/logo.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, 80));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOGIN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikon_blue/BG.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 504));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
                                          
   // Ambil input dari user
String username = tUsername.getText().trim();
        String password = new String(tPassword.getPassword());

// Validasi input kosong
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Username tidak boleh kosong!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            tUsername.requestFocus();
            return;
        }

        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Password tidak boleh kosong!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            tPassword.requestFocus();
            return;
        }

// Panggil LoginDAO untuk cek ke database
        LoginDB loginDAO = new LoginDB();
        User user = loginDAO.login(username, password);

// Cek hasil login
        if (user != null) {
            // ====== TAMBAHKAN INI: Simpan data user ke session ======
            Session.getInstance().setCurrentUser(user);
            // ========================================================

            // Login berhasil
            JOptionPane.showMessageDialog(this,
                    "Login Berhasil!\n\nSelamat datang, " + user.getNama() + "\nRole: " + user.getRole(),
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);

            // Tutup form login
            this.dispose();

            // Arahkan ke form sesuai role
            if (user.getRole().equals("Admin")) {
                new MainFrame().setVisible(true);
            } else if (user.getRole().equals("Guru")) {
                new MainFrame().setVisible(true);
            }

        } else {
            // Login gagal
            JOptionPane.showMessageDialog(this,
                    "Login Gagal!\n\nUsername atau Password salah.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

            // Kosongkan password & focus ke username
            tPassword.setText("");
            tUsername.requestFocus();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void tPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPasswordActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        // TODO add your handling code here:
          if (showPassword.isSelected()) {
            tPassword.setEchoChar((char) 0);
            
        }else{
            tPassword.setEchoChar('•');
        }
        
    }//GEN-LAST:event_showPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JCheckBox showPassword;
    private ClassTambahan.PasswordField tPassword;
    private ClassTambahan.TextField tUsername;
    // End of variables declaration//GEN-END:variables
}
