/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frame;
import ClassAbsensi.Siswa;
import ClassAbsensi.SiswaDAO;
import ClassAbsensi.User;
import PanelPengaturan.dialogUbahUser;
import absensiapp.DialogTambahSiswa;
import absensiapp.dialogUbahSiswa;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

import absensiapp.DialogTambahSiswa;
import absensiapp.dialogUbahSiswa;
/**
 *
 * @author MyBook Hype AMD
 */
public class panelSiswa extends javax.swing.JPanel {
private SiswaDAO siswaDAO;
    /**
     * Creates new form panelSiswa
     */
    public panelSiswa() {
        initComponents();
        siswaDAO = new SiswaDAO();
        loadComboBoxKelas(); // Load kelas dari database
        tampilkanDataSiswa();
    }

    private void tampilkanDataSiswa() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("NIS");
        model.addColumn("Nama Siswa");
        model.addColumn("Kelas");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Status");  // ✅ Tambah kolom status

        List<Siswa> listSiswa = siswaDAO.getAllSiswa();
        int no = 1;
        for (Siswa siswa : listSiswa) {
            model.addRow(new Object[]{
                no++,
                siswa.getNis(),
                siswa.getNamaSiswa(),
                siswa.getIdKelas(),
                siswa.getJenisKelamin(),
                siswa.getStatus() // ✅ Tampilkan status
            });
        }
        tblSiswa.setModel(model);
    }

    private void filterSiswaByKelas() {
        // Ambil id_kelas yang dipilih dari ComboBox
        int idKelas;
        idKelas = Integer.parseInt(cbFilter.getSelectedItem().toString());

        if (idKelas > 0) {
            // Panggil method getSiswaByKelas dari SiswaDB
            SiswaDAO siswaDB = new SiswaDAO();
            List<Siswa> listSiswa = siswaDB.getSiswaByKelas(idKelas);

            // Tampilkan data ke table
            loadTableData(listSiswa);
        } else {
            // Jika "Semua Kelas" dipilih, tampilkan semua siswa
            loadAllSiswa();
        }
    }

    private void loadTableData(List<Siswa> listSiswa) {
        DefaultTableModel model = (DefaultTableModel) tblSiswa.getModel();
        model.setRowCount(0);

        int no = 1;
        for (Siswa siswa : listSiswa) {
            model.addRow(new Object[]{
                no++, // No
                siswa.getNis(), // NIS
                siswa.getNamaSiswa(), // Nama Siswa
                siswa.getIdKelas(), // Kelas
                siswa.getJenisKelamin() // Jenis Kelamin
            });
        }
    }

    private void loadAllSiswa() {
        SiswaDAO siswaDB = new SiswaDAO();
        List<Siswa> listSiswa = siswaDB.getAllSiswa();
        loadTableData(listSiswa);
    }

    private void loadComboBoxKelas() {
        cbFilter.removeAllItems();
        cbFilter.addItem("-- Semua Kelas --");

        List<Integer> listKelas = siswaDAO.getDistinctKelas();

        for (Integer idKelas : listKelas) {
            cbFilter.addItem(idKelas.toString());
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbFilter = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSiswa = new javax.swing.JTable();
        bUbah = new javax.swing.JButton();
        bTambah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bReset = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Filter");

        cbFilter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kelas 1", "Kelas 2", "Kelas 3", "Kelas 4", "Kelas 5", "Kelas 6" }));
        cbFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFilterActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Search :");

        tCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCariActionPerformed(evt);
            }
        });
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCariKeyReleased(evt);
            }
        });

        tblSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSiswa);

        bUbah.setBackground(new java.awt.Color(245, 158, 11));
        bUbah.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bUbah.setForeground(new java.awt.Color(255, 255, 255));
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bTambah.setBackground(new java.awt.Color(34, 197, 94));
        bTambah.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bTambah.setForeground(new java.awt.Color(255, 255, 255));
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bHapus.setBackground(new java.awt.Color(239, 68, 68));
        bHapus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bReset.setBackground(new java.awt.Color(100, 116, 139));
        bReset.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bReset.setForeground(new java.awt.Color(255, 255, 255));
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 41, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addComponent(cbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
      new dialogUbahSiswa().setVisible(true);
    }//GEN-LAST:event_bUbahActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
      new DialogTambahSiswa().setVisible(true);
    }//GEN-LAST:event_bTambahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        int selectedRow = tblSiswa.getSelectedRow();
if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this,
            "Pilih data siswa yang akan dinonaktifkan!",
            "Peringatan",
            JOptionPane.WARNING_MESSAGE);
    return;
}

// Ambil data dari baris yang dipilih
int nis = Integer.parseInt(tblSiswa.getValueAt(selectedRow, 1).toString());
String namaSiswa = tblSiswa.getValueAt(selectedRow, 2).toString();

// Konfirmasi nonaktifkan
int confirm = JOptionPane.showConfirmDialog(this,
        "Apakah Anda yakin ingin menonaktifkan siswa ini?\n\n"
        + "NIS  : " + nis + "\n"
        + "Nama : " + namaSiswa + "\n\n"
        + "Data siswa dan riwayat absensi tetap tersimpan.",
        "Konfirmasi Nonaktifkan Siswa",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);

if (confirm == JOptionPane.YES_OPTION) {
    SiswaDAO siswaDAO = new SiswaDAO();
    boolean success = siswaDAO.nonaktifkanSiswa(nis);
    
    if (success) {
        JOptionPane.showMessageDialog(this,
                "√ Siswa berhasil dinonaktifkan!",
                "Berhasil",
                JOptionPane.INFORMATION_MESSAGE);
        // Load ulang langsung dari database
        List<Siswa> listSiswa = siswaDAO.getAllSiswa();
        loadTableData(listSiswa);
    } else {
        JOptionPane.showMessageDialog(this,
                "✗ Gagal menonaktifkan siswa!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
}
loadAllSiswa();

    }//GEN-LAST:event_bHapusActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
      // Reset filter
        cbFilter.setSelectedIndex(0);
        tCari.setText("");

        // Load ulang langsung dari database
        List<Siswa> listSiswa = siswaDAO.getAllSiswa();
        loadTableData(listSiswa);

        JOptionPane.showMessageDialog(this, "Filter dan pencarian telah direset!",
                "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bResetActionPerformed

    private void cbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFilterActionPerformed

        Object selectedItem = cbFilter.getSelectedItem();

        if (selectedItem == null) {
            // Jika null, tampilkan semua siswa atau return
            List<Siswa> listSiswa = siswaDAO.getAllSiswa();
            loadTableData(listSiswa);
            return;
        }

        String selected = selectedItem.toString();
        List<Siswa> listSiswa;

        // Cek apakah pilihan adalah "-- Semua Kelas --" atau angka kelas
        if (selected.equals("-- Semua Kelas --") || cbFilter.getSelectedIndex() == 0) {
            // Tampilkan semua siswa
            listSiswa = siswaDAO.getAllSiswa();
        } else {
            // Parse String ke Integer dan filter berdasarkan kelas
            try {
                int idKelas = Integer.parseInt(selected);
                listSiswa = siswaDAO.getSiswaByKelas(idKelas);
            } catch (NumberFormatException e) {
                // Jika parsing gagal, tampilkan semua siswa
                listSiswa = siswaDAO.getAllSiswa();
            }
        }

        loadTableData(listSiswa);
    }//GEN-LAST:event_cbFilterActionPerformed

    private void tblSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSiswaMouseClicked
        int baris = tblSiswa.rowAtPoint(evt.getPoint());

        if (baris >= 0) {
            // Highlight baris yang dipilih
            tblSiswa.setRowSelectionInterval(baris, baris);

            // Enable tombol Ubah dan Hapus
            bUbah.setEnabled(true);
            bHapus.setEnabled(true);

            // Jika double click, langsung buka dialog edit
            if (evt.getClickCount() == 2) {
                bUbahActionPerformed(null);
            }
        }

        
    }//GEN-LAST:event_tblSiswaMouseClicked

    private void tCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCariActionPerformed

    private void tCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyReleased
       TableRowSorter<TableModel> rowSorter;
    DefaultTableModel model = (DefaultTableModel) tblSiswa.getModel();
    rowSorter = new TableRowSorter<>(model);
    tblSiswa.setRowSorter(rowSorter);
    String text = tCari.getText();
    
    if (text.trim().length() == 0) {
        rowSorter.setRowFilter(null); // tampilkan semua data
    } else {
        rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text)); // filter, ignore case
    }
    }//GEN-LAST:event_tCariKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JComboBox<String> cbFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCari;
    private javax.swing.JTable tblSiswa;
    // End of variables declaration//GEN-END:variables
}
