/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frame;
import ClassAbsensi.GenerateQRKelas;
import ClassAbsensi.Kelas;
import java.awt.Desktop;
import java.io.File;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author luthfia
 */
public class panelGenerateQR extends javax.swing.JPanel {
private GenerateQRKelas generateQR;
    /**
     * Creates new form panelGenerateQR
     */
    public panelGenerateQR() {
        initComponents();
        generateQR = new GenerateQRKelas();
        loadTotalSiswa();
        loadComboBoxKelas();
    }
private void loadTotalSiswa() {
        int total = generateQR.getTotalSiswaAktif();
        lblTotalSiswa.setText(String.valueOf(total));
    }
    
    /**
     * Load data kelas ke combobox
     */
    private void loadComboBoxKelas() {
        List<Kelas> listKelas = generateQR.getListKelas();
        
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("-- Pilih Kelas --");
        
        for (Kelas kelas : listKelas) {
            String item = "Kelas " + kelas.getTingkat() + " - " + kelas.getTahunAjaran() + " [ID: " + kelas.getIdKelas() + "]";
            model.addElement(item);
        }
        
        cKelas.setModel(model);
    }
    
    /**
     * Extract ID kelas dari combobox item
     */
    private int extractIdKelas(String comboItem) {
        String idStr = comboItem.substring(comboItem.lastIndexOf("[ID: ") + 5, comboItem.lastIndexOf("]"));
        return Integer.parseInt(idStr);
    }

    /**
     * Creates new form panelGenerateQR
     */
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnGeneratePerKelas = new javax.swing.JButton();
        cKelas = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnGenerateSemua = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblTotalSiswa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Generate QR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1206, 536));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel3.setPreferredSize(new java.awt.Dimension(532, 365));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(156, 46, 179));
        jLabel5.setText("Generate per kelas");

        btnGeneratePerKelas.setBackground(new java.awt.Color(156, 46, 179));
        btnGeneratePerKelas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnGeneratePerKelas.setForeground(new java.awt.Color(255, 255, 255));
        btnGeneratePerKelas.setText("Download QR Per Kelas");
        btnGeneratePerKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratePerKelasActionPerformed(evt);
            }
        });

        cKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGeneratePerKelas, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                            .addComponent(cKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(cKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGeneratePerKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel4.setPreferredSize(new java.awt.Dimension(532, 365));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(156, 46, 179));
        jLabel4.setText("Generate semua siswa");

        btnGenerateSemua.setBackground(new java.awt.Color(156, 46, 179));
        btnGenerateSemua.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnGenerateSemua.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateSemua.setText("Download QR Semua Siswa");
        btnGenerateSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateSemuaActionPerformed(evt);
            }
        });

        jLabel6.setText("Total Jumlah Siswa:");

        lblTotalSiswa.setText("1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnGenerateSemua, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTotalSiswa))
                .addGap(22, 22, 22)
                .addComponent(btnGenerateSemua, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(156, 46, 179));
        jLabel2.setText("Generate Qr Code");

        jLabel3.setText("Generate dan Simpan QR berdasarkan kode unik siswa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateSemuaActionPerformed
        // TODO add your handling code here:
        int total = generateQR.getTotalSiswaAktif();
        
        if (total == 0) {
            JOptionPane.showMessageDialog(this,
                "Tidak ada siswa aktif untuk di-generate!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this,
            "Generate QR untuk " + total + " siswa dari semua kelas?\n" +
            "File akan disimpan dalam format ZIP, dikelompokkan per kelas.",
            "Konfirmasi Generate",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih Folder Penyimpanan");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home") + "/Downloads"));
        
        int result = fileChooser.showSaveDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            String outputFolder = fileChooser.getSelectedFile().getAbsolutePath();
            
            btnGenerateSemua.setEnabled(false);
            
            btnGenerateSemua.setText("Generating...");
            
            new Thread(() -> {
                boolean success = generateQR.generateAllKelas(outputFolder);
                
                javax.swing.SwingUtilities.invokeLater(() -> {
                    btnGenerateSemua.setEnabled(true);
                    
                    btnGenerateSemua.setText("Generate QR");
                    
                    if (success) {
                        int open = JOptionPane.showConfirmDialog(this,
                            "✓ QR Code berhasil di-generate!\n\n" +
                            "File: QR_Semua_Kelas.zip\n" +
                            "Lokasi: " + outputFolder + "\n\n" +
                            "Buka folder?",
                            "Sukses",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.INFORMATION_MESSAGE);
                        
                        if (open == JOptionPane.YES_OPTION) {
                            try {
                                Desktop.getDesktop().open(new File(outputFolder));
                            } catch (Exception e) {
                                e.printStackTrace();
                                JOptionPane.showMessageDialog(this,
                                    "Tidak dapat membuka folder secara otomatis.\n" +
                                    "Silakan buka manual: " + outputFolder,
                                    "Info",
                                    JOptionPane.INFORMATION_MESSAGE);
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(this,
                            "✗ Gagal generate QR Code!\n\n" +
                            "Kemungkinan penyebab:\n" +
                            "- Tidak ada kelas atau siswa aktif\n" +
                            "- Folder tujuan tidak dapat diakses\n" +
                            "- Error pada proses generate",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    }
                });
            }).start();
        }
    }//GEN-LAST:event_btnGenerateSemuaActionPerformed

    private void btnGeneratePerKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePerKelasActionPerformed
        // TODO add your handling code here:
        if (cKelas.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this,
                "Silakan pilih kelas terlebih dahulu!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String selected = cKelas.getSelectedItem().toString();
        int idKelas = extractIdKelas(selected);
        
        int jumlahSiswa = generateQR.getJumlahSiswaByKelas(idKelas);
        
        if (jumlahSiswa == 0) {
            JOptionPane.showMessageDialog(this,
                "Kelas ini tidak memiliki siswa aktif!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this,
            "Generate QR untuk " + jumlahSiswa + " siswa di kelas ini?\n" +
            "File akan disimpan dalam format ZIP.",
            "Konfirmasi Generate",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih Folder Penyimpanan");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home") + "/Downloads"));
        
        int result = fileChooser.showSaveDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            String outputFolder = fileChooser.getSelectedFile().getAbsolutePath();
            
            btnGeneratePerKelas.setEnabled(false);
            
            btnGeneratePerKelas.setText("Generating...");
            
            new Thread(() -> {
                boolean success = generateQR.generateByKelas(idKelas, outputFolder);
                
                javax.swing.SwingUtilities.invokeLater(() -> {
                    btnGeneratePerKelas.setEnabled(true);
                    
                    btnGeneratePerKelas.setText("Generate QR Per Kelas");
                    
                    if (success) {
                        int open = JOptionPane.showConfirmDialog(this,
                            "✓ QR Code berhasil di-generate!\n\n" +
                            "File: QR_Kelas_" + idKelas + ".zip\n" +
                            "Lokasi: " + outputFolder + "\n\n" +
                            "Buka folder?",
                            "Sukses",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.INFORMATION_MESSAGE);
                        
                        if (open == JOptionPane.YES_OPTION) {
                            try {
                                Desktop.getDesktop().open(new File(outputFolder));
                            } catch (Exception e) {
                                e.printStackTrace();
                                JOptionPane.showMessageDialog(this,
                                    "Tidak dapat membuka folder secara otomatis.\n" +
                                    "Silakan buka manual: " + outputFolder,
                                    "Info",
                                    JOptionPane.INFORMATION_MESSAGE);
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(this,
                            "✗ Gagal generate QR Code!\n\n" +
                            "Pastikan kelas memiliki siswa aktif.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    }
                });
            }).start();
        }
    }//GEN-LAST:event_btnGeneratePerKelasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeneratePerKelas;
    private javax.swing.JButton btnGenerateSemua;
    private javax.swing.JComboBox<String> cKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblTotalSiswa;
    // End of variables declaration//GEN-END:variables
}
